---
#
# Operator image
#

- name: Compute local imagestreamtag name
  set_fact:
    operator_imagestreamtag: "gpu-operator-ci:operator_{{ gpu_operator_image_tag }}"

- name: Compute local image name
  set_fact:
    operator_image_name: "image-registry.openshift-image-registry.svc:5000/gpu-operator-ci/{{ operator_imagestreamtag }}"

- name: Check if the operator image already exists
  command: oc get "imagestreamtag/{{ operator_imagestreamtag }}" -n gpu-operator-ci
  failed_when: false
  register: has_operator_image

- name: Build the operator image
  when: has_operator_image.rc != 0
  block:
  - name: The operator image does not exist, build it
    debug: msg="The operator image does not exist, build it"

  - name: Apply the operator image builder script manifest
    command: oc apply -f "{{ gpu_operator_image_builder_script }}"

  - name: Instantiate the template of the image builder Pod
    template:
      src: "{{ gpu_operator_image_builder_pod }}"
      dest: "{{ artifact_extra_logs_dir }}/operator-image-builder-pod.yml"
      mode: 0400

  - name: Delete the operator image builder pod, if any
    command: oc delete -f "{{ artifact_extra_logs_dir }}/operator-image-builder-pod.yml" --ignore-not-found=true

  - name: Name the namespace privileged
    command: oc adm policy add-scc-to-user privileged -z default -n gpu-operator-ci

  - name: Apply the operator image builder pod manifest
    command:
      oc apply -f "{{ artifact_extra_logs_dir }}/operator-image-builder-pod.yml"

  - block:
    - name: Wait for the operator image to be built
      command:
        oc get pod/operator-image-builder-pod
           --no-headers
           -ocustom-columns=phase:status.phase
           -n gpu-operator-ci
      register: wait_image_builder_pod
      until: "'Succeeded' in wait_image_builder_pod.stdout or 'Failed' in wait_image_builder_pod.stdout or 'Error' in wait_image_builder_pod.stdout"
      retries: 40
      delay: 30

    - name: Fail if the operator image failed to be built
      when: "'Failed' in wait_image_builder_pod.stdout or 'Error' in wait_image_builder_pod.stdout"
      fail: msg="The operator image failed to build"
    always:
    - name: Store the logs of operator image build (debug)
      shell:
        oc logs pod/operator-image-builder-pod -n gpu-operator-ci
           > {{ artifact_extra_logs_dir }}/operator-image-builder-pod.log
      failed_when: false

    rescue:
    - name: Get info about the operator image build failure (debug)
      command: oc get pods -n gpu-operator-ci
      failed_when: false

    - name: Get the description of the helper image build failure
      shell:
        oc describe pod/operator-image-builder-pod -n gpu-operator-ci
           > {{ artifact_extra_logs_dir }}/operator-image-builder-pod.descr
      failed_when: false

    - name: Fail because the operator image failed to build
      fail: msg="Fail because the operator image failed to build"
